name: garage
channels:
  - conda-forge
dependencies:
    - python==3.6.6
    - numpy==1.14.5 # pycma requires numpy to install (smh)
    - pip==19.0.3
    - pip:
        - -e .[all]
        - -e .[dev]
        # install sister packages to make sure environments stay compatible
        #- git+https://github.com/rlworkgroup/metaworlds.git@master#egg=metaworlds
        #- git+https://github.com/rlworkgroup/viskit.git@master#egg=viskit
